let registry, hardware, installed = [], projects = [], task = 'text', selectedEngine = null, runtimeStatus = {}, mediaFile = null, subtitleFile = null, videoImages = [], videoAudio = null, videoSubtitle = null;
const tasks = [['text','Text & Script'],['image','Image'],['voice','Voice'],['caption','Captions'],['video','Video']];
const $ = selector => document.querySelector(selector);
const mode = () => document.querySelector('input[name=mode]:checked').value;
const installedModel = id => installed.find(model => model.id === id);
function compatibility(engine){const reasons=[];if(hardware.ramGb<engine.minRamGb)reasons.push(`${engine.minRamGb} GB RAM`);if(hardware.vramGb<engine.minVramGb)reasons.push(`${engine.minVramGb} GB VRAM`);if(hardware.freeDiskGb<engine.diskGb)reasons.push(`${engine.diskGb} GB disk`);if(engine.gpu!=='any'&&!hardware.gpuVendor.includes(engine.gpu))reasons.push(`${engine.gpu.toUpperCase()} GPU`);return reasons}
const choicesFor = tool => registry.engines.filter(e=>e.tasks.includes(tool)).map(e=>({...e,reasons:compatibility(e)})).sort((a,b)=>(a.reasons.length-b.reasons.length)||(b.quality-a.quality)||(b.speed-a.speed));
function message(text, error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error)}
async function renderGallery(project){const outputs=project?.outputs?.filter(output=>['image','video'].includes(output.task)).slice(0,12)||[];const cards=await Promise.all(outputs.map(async output=>{const file=output.content.replaceAll('&','&amp;').replaceAll('"','&quot;');if(output.task==='video')return `<figure><div class="video-tile">▶</div><figcaption><button data-video-open="${file}">Preview</button><button data-video-export="${file}">Export</button></figcaption></figure>`;try{const source=await window.studio.imageData(output.content);return `<figure><img src="${source}" alt="Generated image"><figcaption><span>${new Date(output.createdAt).toLocaleDateString()}</span><button data-export="${file}">Export</button></figcaption></figure>`}catch{return ''}}));$('#gallery').innerHTML=cards.join('');document.querySelectorAll('[data-export]').forEach(button=>button.onclick=async()=>{const saved=await window.studio.exportImage(button.dataset.export);if(saved)message(`Image exported to ${saved}`)});document.querySelectorAll('[data-video-open]').forEach(button=>button.onclick=()=>window.studio.openVideo(button.dataset.videoOpen));document.querySelectorAll('[data-video-export]').forEach(button=>button.onclick=async()=>{const saved=await window.studio.exportVideo(button.dataset.videoExport);if(saved)message(`Video exported to ${saved}`)})}
function renderProjects(){const current=$('#project').value;$('#project').innerHTML=projects.map(project=>`<option value="${project.id}">${project.name}</option>`).join('');if(projects.some(p=>p.id===current))$('#project').value=current;const project=projects.find(p=>p.id===$('#project').value);$('#history').innerHTML=project?.outputs?.slice(0,6).map(output=>`<p><strong>${output.task}</strong> · ${new Date(output.createdAt).toLocaleString()}</p>`).join('')||'<p>No output history yet.</p>';renderGallery(project)}
function render(){
 $('#hardware').innerHTML=`<strong>${hardware.ramGb} GB RAM</strong><span>${hardware.gpuName}</span><span>${hardware.vramGb} GB VRAM · ${hardware.freeDiskGb} GB free</span>`;
 $('#tools').innerHTML=tasks.map(([id,name])=>`<button class="${task===id?'selected':''}" data-task="${id}">${name}</button>`).join('');
 $('#image-controls').classList.toggle('visible',task==='image');$('#video-controls').classList.toggle('visible',task==='video');$('#media').hidden=task!=='caption';$('#media-name').hidden=task!=='caption';
 const choices=choicesFor(task);
 $('#engines').innerHTML=choices.length?choices.map((e,i)=>{const model=installedModel(e.id),external=runtimeStatus[e.id]?.ready,active=model?.activeFor.includes(task)||selectedEngine?.id===e.id,best=!e.reasons.length&&i===0,status=e.adapter?(external?'Runtime ready':runtimeStatus[e.id]?.reason||'Checking runtime…'):(model?'Installed':'Not installed');return `<article class="${best?'recommended':''}"><div><h3>${e.name}</h3><p>${e.reasons.length?'Not compatible: '+e.reasons.join(', '):'Compatible · '+e.diskGb+' GB package'} · ${status}</p></div><span>${active?'Active':best?'Recommended':e.quality+'/5 quality'}</span><div class="actions">${model?`<button data-activate="${e.id}" ${e.reasons.length||active?'disabled':''}>${active?'Selected':'Select'}</button><button class="secondary" data-remove="${e.id}" ${active?'disabled':''}>Remove</button>`:external?`<button data-runtime-select="${e.id}" ${active?'disabled':''}>${active?'Selected':'Select'}</button>`:`<button data-install="${e.id}" ${e.reasons.length?'disabled':''}>${e.packages?'Install':'Import'}</button>`}</div></article>`}).join(''):'<p>No registered engine for this tool.</p>';
 document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{task=b.dataset.task;selectedEngine=null;render()});
 document.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>install(b.dataset.install));
 document.querySelectorAll('[data-activate]').forEach(b=>b.onclick=()=>activate(b.dataset.activate));
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>remove(b.dataset.remove));
 document.querySelectorAll('[data-runtime-select]').forEach(b=>b.onclick=()=>{selectedEngine=registry.engines.find(e=>e.id===b.dataset.runtimeSelect);message('Local runtime selected.');render()});
}
async function install(id){try{const engine=registry.engines.find(e=>e.id===id);if(engine.licenseAcceptance&&!window.confirm(`${engine.name} downloads a separately licensed model (${engine.packages.model.license}, about 4.3 GB). Continue only if you accept its usage restrictions.`))return;message(`Installing ${engine.name}…`);if(engine.packages){await window.studio.installRuntime(id);await scan();message(`${engine.name} verified and installed.`);return}if(!engine.sha256)throw new Error('Verified package manifest is not published yet.');const result=engine.downloadUrl?await window.studio.downloadModel(id):await window.studio.importModel(id);if(result){installed=await window.studio.listModels();message(`${engine.name} verified and installed.`);render()}}catch(error){message(error.message,true)}}
async function activate(id){try{await window.studio.activateModel(task,id);installed=await window.studio.listModels();selectedEngine=registry.engines.find(engine=>engine.id===id);message('Engine selected for this tool.');render()}catch(error){message(error.message,true)}}
async function remove(id){try{await window.studio.removeModel(id);installed=await window.studio.listModels();message('Model removed safely.');render()}catch(error){message(error.message,true)}}
async function generate(){try{if(!selectedEngine)throw new Error('Select a ready engine first.');const prompt=$('#prompt').value.trim();if(task==='caption'&&!mediaFile)throw new Error('Select an audio or video file first.');if(task==='video'&&!videoImages.length)throw new Error('Select at least one image for the video.');if(!['caption','video'].includes(task)&&!prompt)throw new Error('Enter generation instructions.');if(!$('#project').value)throw new Error('Create a project first.');$('#generate').disabled=true;$('#result').value='Generating locally…';const imageSize=$('#image-size').value.split('x').map(Number),videoSize=$('#video-size').value.split('x').map(Number);const result=await window.studio.generate(selectedEngine.id,{task,prompt,mediaFile,language:$('#language').value,projectId:$('#project').value,negativePrompt:$('#negative-prompt').value.trim(),width:task==='video'?videoSize[0]:imageSize[0],height:task==='video'?videoSize[1]:imageSize[1],steps:Number($('#steps').value),seed:Number($('#seed').value),imageFiles:videoImages,audioFile:videoAudio,subtitleFile:videoSubtitle,secondsPerImage:Number($('#slide-seconds').value),fps:30});subtitleFile=result.type==='subtitle'?result.content:null;$('#save-subtitle').disabled=!subtitleFile;$('#result').value=result.type==='image'?'Image created and added to project gallery.':result.type==='video'?'MP4 video created and added to project gallery.':result.subtitleText||result.content||JSON.stringify(result,null,2);projects=await window.studio.listProjects();renderProjects()}catch(error){message(error.message,true);$('#result').value='Generation did not complete.'}finally{$('#generate').disabled=false}}
async function scan(){try{$('#status').textContent='Scanning system…';[registry,hardware,installed,projects]=await Promise.all([window.studio.getRegistry(),window.studio.scanHardware(),window.studio.listModels(),window.studio.listProjects()]);if(!projects.length){await window.studio.createProject('My First Project');projects=await window.studio.listProjects()}renderProjects();const checks=await Promise.all(registry.engines.filter(e=>e.adapter).map(async e=>[e.id,await window.studio.engineStatus(e.id)]));runtimeStatus=Object.fromEntries(checks);const compatibleReady=choicesFor(task).find(e=>runtimeStatus[e.id]?.ready&&!e.reasons.length);if(mode()==='auto'&&compatibleReady)selectedEngine=compatibleReady;$('#status').textContent='System scan complete';render()}catch(error){message(error.message,true)}}
$('#rescan').onclick=scan;$('#generate').onclick=generate;$('#project').onchange=renderProjects;$('#new-project').onclick=async()=>{const name=window.prompt('Project name');if(name){await window.studio.createProject(name);projects=await window.studio.listProjects();renderProjects()}};$('#media').onclick=async()=>{mediaFile=await window.studio.selectMedia();$('#media-name').textContent=mediaFile?mediaFile.split(/[\\/]/).pop():''};$('#video-images').onclick=async()=>{videoImages=await window.studio.selectVideoImages();$('#video-images-name').textContent=videoImages.length?`${videoImages.length} image(s) selected`:'No images selected'};$('#video-audio').onclick=async()=>{videoAudio=await window.studio.selectVideoAudio();message(videoAudio?'Soundtrack selected.':'Soundtrack cleared.')};$('#video-subtitle').onclick=async()=>{videoSubtitle=await window.studio.selectVideoSubtitle();message(videoSubtitle?'Subtitles selected.':'Subtitles cleared.')};$('#save-subtitle').onclick=async()=>{try{await window.studio.saveSubtitle(subtitleFile,$('#result').value);message('Edited subtitle saved.')}catch(error){message(error.message,true)}};document.querySelectorAll('input[name=mode]').forEach(r=>r.onchange=render);scan();
