let registry, hardware, installed = [], task = 'text', selectedEngine = null, runtimeStatus = {};
const tasks = [['text','Text & Script'],['image','Image'],['voice','Voice'],['caption','Captions'],['video','Video']];
const $ = selector => document.querySelector(selector);
const mode = () => document.querySelector('input[name=mode]:checked').value;
const installedModel = id => installed.find(model => model.id === id);
function compatibility(engine){const reasons=[];if(hardware.ramGb<engine.minRamGb)reasons.push(`${engine.minRamGb} GB RAM`);if(hardware.vramGb<engine.minVramGb)reasons.push(`${engine.minVramGb} GB VRAM`);if(hardware.freeDiskGb<engine.diskGb)reasons.push(`${engine.diskGb} GB disk`);if(engine.gpu!=='any'&&!hardware.gpuVendor.includes(engine.gpu))reasons.push(`${engine.gpu.toUpperCase()} GPU`);return reasons}
function message(text, error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error)}
function render(){
 $('#hardware').innerHTML=`<strong>${hardware.ramGb} GB RAM</strong><span>${hardware.gpuName}</span><span>${hardware.vramGb} GB VRAM · ${hardware.freeDiskGb} GB free</span>`;
 $('#tools').innerHTML=tasks.map(([id,name])=>`<button class="${task===id?'selected':''}" data-task="${id}">${name}</button>`).join('');
 const choices=registry.engines.filter(e=>e.tasks.includes(task)).map(e=>({...e,reasons:compatibility(e)})).sort((a,b)=>(a.reasons.length-b.reasons.length)||(b.quality-a.quality));
 $('#engines').innerHTML=choices.length?choices.map((e,i)=>{const model=installedModel(e.id),external=runtimeStatus[e.id]?.ready,active=model?.activeFor.includes(task)||selectedEngine?.id===e.id,best=!e.reasons.length&&i===0,status=e.adapter?(external?'Runtime ready':runtimeStatus[e.id]?.reason||'Checking runtime…'):(model?'Installed':'Not installed');return `<article class="${best?'recommended':''}"><div><h3>${e.name}</h3><p>${e.reasons.length?'Not compatible: '+e.reasons.join(', '):'Compatible · '+e.diskGb+' GB package'} · ${status}</p></div><span>${active?'Active':best?'Recommended':e.quality+'/5 quality'}</span><div class="actions">${model?`<button data-activate="${e.id}" ${e.reasons.length||active?'disabled':''}>${active?'Selected':'Select'}</button><button class="secondary" data-remove="${e.id}" ${active?'disabled':''}>Remove</button>`:external?`<button data-runtime-select="${e.id}" ${active?'disabled':''}>${active?'Selected':'Select'}</button>`:`<button data-install="${e.id}" ${e.reasons.length?'disabled':''}>${e.downloadUrl?'Install':'Import'}</button>`}</div></article>`}).join(''):'<p>No registered engine for this tool.</p>';
 document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{task=b.dataset.task;selectedEngine=null;render()});
 document.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>install(b.dataset.install));
 document.querySelectorAll('[data-activate]').forEach(b=>b.onclick=()=>activate(b.dataset.activate));
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>remove(b.dataset.remove));
 document.querySelectorAll('[data-runtime-select]').forEach(b=>b.onclick=()=>{selectedEngine=registry.engines.find(e=>e.id===b.dataset.runtimeSelect);message('Local runtime selected.');render()});
}
async function install(id){try{const engine=registry.engines.find(e=>e.id===id);if(!engine.sha256)throw new Error('Verified package manifest is not published yet.');const result=engine.downloadUrl?await window.studio.downloadModel(id):await window.studio.importModel(id);if(result){installed=await window.studio.listModels();message(`${engine.name} verified and installed.`);render()}}catch(error){message(error.message,true)}}
async function activate(id){try{await window.studio.activateModel(task,id);installed=await window.studio.listModels();selectedEngine=registry.engines.find(engine=>engine.id===id);message('Engine selected for this tool.');render()}catch(error){message(error.message,true)}}
async function remove(id){try{await window.studio.removeModel(id);installed=await window.studio.listModels();message('Model removed safely.');render()}catch(error){message(error.message,true)}}
async function generate(){try{if(!selectedEngine)throw new Error('Select a ready engine first.');const prompt=$('#prompt').value.trim();if(!prompt)throw new Error('Enter generation instructions.');$('#generate').disabled=true;$('#result').textContent='Generating locally…';const result=await window.studio.generate(selectedEngine.id,{task,prompt});$('#result').textContent=result.content||JSON.stringify(result,null,2)}catch(error){message(error.message,true);$('#result').textContent='Generation did not complete.'}finally{$('#generate').disabled=false}}
async function scan(){try{$('#status').textContent='Scanning system…';[registry,hardware,installed]=await Promise.all([window.studio.getRegistry(),window.studio.scanHardware(),window.studio.listModels()]);const checks=await Promise.all(registry.engines.filter(e=>e.adapter).map(async e=>[e.id,await window.studio.engineStatus(e.id)]));runtimeStatus=Object.fromEntries(checks);const compatibleReady=registry.engines.find(e=>e.tasks.includes(task)&&runtimeStatus[e.id]?.ready&&!compatibility(e).length);if(mode()==='auto'&&compatibleReady)selectedEngine=compatibleReady;$('#status').textContent='System scan complete';render()}catch(error){message(error.message,true)}}
$('#rescan').onclick=scan;$('#generate').onclick=generate;document.querySelectorAll('input[name=mode]').forEach(r=>r.onchange=render);scan();
