<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Smart AI Tools | C-Net AI Studio</title><style>
*{box-sizing:border-box}body{margin:0;background:#050811;color:#fff;font-family:Inter,system-ui,Arial}.wrap{max-width:1180px;margin:auto;padding:30px}.top{display:flex;justify-content:space-between;align-items:center;gap:15px}.top a,.link{color:#5cddff;text-decoration:none}.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:22px}.card{background:#0c1424;border:1px solid #223252;border-radius:20px;padding:22px;margin-top:22px}label{display:block;color:#9facbf;margin:14px 0 6px}input,select,textarea{width:100%;padding:13px;border:1px solid #334566;border-radius:11px;background:#07101e;color:#fff}textarea{min-height:220px;resize:vertical}button{margin-top:16px;padding:13px 19px;border:0;border-radius:11px;background:linear-gradient(90deg,#04c9ff,#7061ff,#d94ce9);color:white;font-weight:800}.doc{padding:13px 0;border-bottom:1px solid #1c2940}.muted{color:#8e9cb7}.success{padding:12px;background:#113322;border-radius:10px;color:#82efaa}@media(max-width:800px){.grid{grid-template-columns:1fr}.wrap{padding:18px}}
</style></head><body><div class="wrap"><div class="top"><div><div class="muted">BATCH 8 · SMART AI TOOLS</div><h1>Script, Scene, Caption & Prompt Studio</h1></div><a href="{{ route('studio.dashboard') }}">← Dashboard</a></div>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
<div class="grid"><section class="card"><form method="POST" action="{{ route('studio.smart-tools.generate') }}">@csrf
<label>Tool</label><select name="tool_type"><option value="script">AI Script Builder</option><option value="scenes">Smart Scene Planner</option><option value="captions">Auto Caption Builder</option><option value="prompt">Prompt Enhancer</option></select>
<label>Title</label><input name="title" required maxlength="150" placeholder="Campaign or content title">
<label>Language</label><select name="language"><option value="en">English</option><option value="hi">हिन्दी</option></select>
<label>Your idea or source text</label><textarea name="source_text" required maxlength="30000" placeholder="Describe your video, advertisement, lesson or reel…"></textarea>
<button>Generate Smart Content</button></form></section>
<aside class="card"><h2>Recent documents</h2>@forelse($documents as $document)<div class="doc"><a class="link" href="{{ route('studio.smart-tools.show', $document) }}">{{ $document->title }}</a><div class="muted">{{ strtoupper($document->tool_type) }} · {{ $document->updated_at->diffForHumans() }}</div></div>@empty<p class="muted">Your generated documents will appear here.</p>@endforelse</aside></div></div></body></html>
